#!/bin/bash -e
### BEGIN INIT INFO
# Provides:          jenkins-swarm-client
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: jenkins-swarm-client
# Description:       Automatically connect to a Jenkins Master and register as a slave.
### END INIT INFO
#
# jenkins-swarm-client    This init.d script is used to start jenkins-swarm-client agent

ENV="env -i LANG=C PATH=/sbin:/usr/sbin:/bin:/usr/bin DISPLAY=:99"

SWARM_NAME="-name $(uname -n)"
SWARM_UID=builder
SWARM_JAR=/home/builder/swarm-client.jar
SWARM_USERNAME="-username {{JenkinsAdminUsername}}"
SWARM_PASSWORD="-password {{JenkinsAdminPassword}}"
SWARM_MASTER="-master http://{{JenkinsJNPLDNSName}}:8080"
SWARM_FSROOT="-fsroot /home/builder/jobs"

SWARM_CLIENT_CMD="/usr/bin/java -jar $SWARM_JAR $SWARM_NAME $SWARM_USERNAME $SWARM_PASSWORD $SWARM_MASTER $SWARM_FSROOT"
PIDFILE=/var/run/jenkins-swarm-client.pid
IS_ACTIVE=1

if [ -s $PIDFILE ]; then
    PID=$(cat $PIDFILE)
    if ps -p $PID > /dev/null 2>&1 ; then
        IS_ACTIVE=0
    else
        IS_ACTIVE=1
    fi
else
    if pgrep -f $SWARM_JAR -U $SWARM_UID > /dev/null 2>&1; then
        IS_ACTIVE=0
        PID=$(pgrep -f $SWARM_JAR -U $SWARM_UID | head -1)
    else
        IS_ACTIVE=1
    fi
fi

stop() {
    if [ ${IS_ACTIVE} -eq 0 ]; then
        echo "Stopping jenkins-swarm-client (pid $PID)"
        kill $PID
        IS_ACTIVE=1
    else
        echo "jenkins-swarm-client is already stopped..."
    fi
}

start() {
    if [ ${IS_ACTIVE} -eq 0 ]; then
        echo "jenkins-swarm-client is already running..."
    else
        echo "Starting jenkins-swarm-client: $ENV sudo -E -u $SWARM_UID  $SWARM_CLIENT_CMD"
        $ENV sudo -E -u $SWARM_UID $SWARM_CLIENT_CMD &
        sleep 2
        pgrep -f $SWARM_JAR -U $SWARM_UID | head -1 > $PIDFILE
    fi
}

case $1 in
    start)
        start
    ;;
    stop)
        stop
    ;;
    restart)
        echo 'Restarting jenkins-swarm-client'
        stop
        start
    ;;
    status)
        if [ ${IS_ACTIVE} -eq 0 ]; then
            echo "jenkins-swarm-client is running"
            exit 0
        else
            echo "jenkins-swarm-client is NOT running."
            exit 1
        fi
    ;;
    *)
        echo "Usage: /etc/init.d/jenkins-swarm-client {start|stop|restart|status}"
        exit 1
    ;;
esac
