---
- name: Installing default packages
  yum:
    name: '{{item}}'
  with_items:
    - awslogs

- name: Creating templates
  template:
    src: 'templates{{item}}'
    dest: '{{item}}'
    owner: root
    group: root
    mode: 0644
  with_items:
    - /etc/awslogs/awscli.conf
    - /etc/awslogs/awslogs.conf

- name: Enabling services
  service:
    name: '{{item}}'
    state: started
    enabled: yes
  with_items:
    - awslogs
    