---
- name: Installing default packages
  yum: name='amazon-efs-utils'

- name: Creating directory /mnt/application
  file: path=/mnt/application state=directory mode=0755

- name: Mounting EFS
  mount: path=/mnt/application src='{{FileSystem}}' fstype=efs opts=tls state=mounted

- name: Copying backup scripts
  copy: src='files{{item}}' dest='{{item}}' owner=root group=root mode='0700'
  with_items:
    - /root/efs-backup.sh
    - /root/efs-restore.sh
  