---
#
# FILE: main.yaml
#
# DESCRIPTION: This file contains the base configuration for all host in the
#   stack.
#
#
- name: Removing obsolete packages
  yum:
    name: 'ntp*'
    state: absent

- name: Installing default packages
  yum:
    name: '{{item}}'
  with_items:
    - wget
    - htop
    - chrony

- name: Creating template .bashrc
  template:
    src: templates/home/ec2-user/.bashrc
    dest: /home/ec2-user/.bashrc
    owner: root
    group: root
    mode: 0644

- name: Installing and configuring awslogs
  include_role: name=common tasks_from=configure_awslogs

- name: Installing and configuring cfn-hup
  include_role: name=common tasks_from=configure_cfn_hup

- name: Installing and configuring AWS Inspector Agent
  include_role: name=common tasks_from=configure_aws_inspector_agent

- name: Installing and configuring yum-cron
  include_role: name=common tasks_from=configure_yum_cron

- name: Configuring SSH for IAM User Access
  include_role: name=common tasks_from=configure_sshd
  when: 
    - HasIAMUserSSHAccess is defined
    - HasIAMUserSSHAccess == true 

- name: Tagging EC2 Root Volume
  include_role: name=common tasks_from=tag_ec2_root_volume
  
- name: Enabling services
  service:
    name: '{{item}}'
    state: started
    enabled: yes
  with_items:
    - chronyd
