---
#------------------------------------------------------------------------------
#
# FILE: gitlab.yaml
#
# DESCRIPTION: Install Gitlab
#
# ?> ansible-playbook gitlab.yaml --extra-vars=@/root/playbooks/group_vars/stack.yaml
#
- hosts: all
  gather_facts: True
  vars_files: 
    - vars/config.yml
  roles:
    - common
    - gitlab
