language: python
python: "2.7"
cache:
  directories:
    - $HOME/.cache/pip
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install ansible -y
#  - sudo apt-get install ansible-lint -y
script:
  - ansible-playbook --connection=local --syntax-check playbooks/*.yaml
#  - ansible-lint playbooks/*.yaml