language: python
python: "2.7"
cache:
  directories:
    - $HOME/.cache/pip
#install:
#  - pip install -r requirements.txt
#  - pip install -r test-requirements.txt
script:
  - ansible-playbook --syntax-check bastion.yaml
  - ansible-lint bastion.yaml