language: python
python: "2.7"
cache:
  directories:
    - $HOME/.cache/pip
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install ansible -y
  - sudo bash -c "echo $(uname -n) ansible_connection=local > /etc/ansible/hosts"
script:
  - ansible-playbook --version
  - ansible-playbook --syntax-check playbooks/*.yaml
#  - ansible-lint playbooks/*.yaml