---
- name: Removing obsolete packages
  yum:
    name: '{{item}}'
    state: absent
  with_items:
    - java-1.7.0-openjdk

- name: Installing default packages
  yum:
    name: '{{item}}'
  with_items: 
    - jq
    - postfix
    - policycoreutils-python
    - amazon-efs-utils
    - postgresql96-contrib
    - patch
    
- name: Install pip modules
  pip:
    name: psycopg2-binary

- name: Downloading Gitlab repository
  get_url:
    url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.rpm.sh
    dest: /root/gitlab-ee.repo.sh
    mode: 700

- name: Adding Gitlab repository
  shell: /root/gitlab-ee.repo.sh
  args:
    creates: /etc/yum.repos.d/gitlab_gitlab-ee.repo

- name: Creating and mounting EFS
  include_role: name=common tasks_from=create_fs

- name: Monitoring application logs
  include_role: name=common tasks_from=configure_awslogs_extra
  with_items: 
    - { name: 'unicorn_stdout', filename: '/var/log/gitlab/unicorn/unicorn_stdout.log' }
    - { name: 'unicorn_stderr', filename: '/var/log/gitlab/unicorn/unicorn_stderr.log' }
    - { name: 'gitlab-shell', filename: '/var/log/gitlab/gitlab-shell/gitlab-shell.log' }
    - { name: 'nginx-gitlab_error', filename: '/var/log/gitlab/nginx/gitlab_error.log' }
    - { name: 'nginx-gitlab_access', filename: '/var/log/gitlab/nginx/gitlab_access.log' }
    - { name: 'gitlab-rails-application', filename: '/var/log/gitlab/gitlab-rails/application.log' }
  loop_control:
    loop_var: log

- name: Installing Gitlab     
  yum:
    name: gitlab-ee

- name: Templating /etc/gitlab/gitlab.rb
  template: 
    src: 'templates{{item.src}}'
    dest: '{{item.src}}'
    owner: root
    group: root
    mode: '{{item.mode}}'
  with_items:
    - { src: /etc/gitlab/gitlab.rb, mode: '0700' }

- name: Copying /root/config.rb.patch
  copy:
    src: files/root/config.rb.patch
    dest: /root/config.rb.patch
    owner: root
    group: root
    mode: 0644

- name: Patching config.rb...
  patch: 
    src: /root/config.rb.patch
    dest: /opt/gitlab/embedded/service/gitlab-rails/ee/lib/ee/gitlab/auth/ldap/config.rb 

- name: Configuring Gitlab
  shell: 'GITLAB_ROOT_EMAIL="{{GitlabAdminEmail}}" GITLAB_ROOT_PASSWORD="{{GitlabAdminPassword}}" gitlab-ctl reconfigure'

- name: Obtaining token
  uri:
    url: http://localhost:80/oauth/token
    method: POST
    body_format: json
    body:
      grant_type: password
      username: root
      password: '{{GitlabAdminPassword}}'
    status_code: 200
  register: response

- set_fact:
    token: "{{ response.json.access_token }}"

- name: Changing settings
  uri:
    url: 'http://localhost:80/api/v4/application/settings?{{item.key}}={{item.value}}'
    method: PUT
    headers:
      Authorization: 'Bearer {{token}}'
    status_code: 200
  with_items:
    - { key: 'signup_enabled', value: false }
    - { key: 'default_project_visibility', value: 'public' }
    - { key: 'email_author_in_body', value: true }
    - { key: 'gravatar_enabled', value: false }
    - { key: 'help_page_hide_commercial_content', value: true }
    - { key: 'html_emails_enabled', value: true }

- name: Revoking token
  uri:
    url: 'http://localhost:80/oauth/revoke'
    method: POST
    headers:
      Authorization: 'Bearer {{token}}'
    body_format: json
    body:
      token: '{{token}}'
    status_code: 200

- name: restarting gitlab  
  shell: 'gitlab-ctl restart'
  