---
- name: Removing obsolete packages
  yum:
    name: '{{item}}'
    state: absent
  with_items:
    - java-1.7.0-openjdk

- name: Installing Splunk     
  yum: name='https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version=7.1.2&product=splunk&filename=splunk-7.1.2-a0c72a66db66-linux-2.6-x86_64.rpm&wget=true'

- name: Templating Splunk config files
  template: 
    src: 'templates{{item.src}}'
    dest: '{{item.src}}'
    owner: root
    group: root
    mode: '{{item.mode}}'
  with_items:
    - { src: /opt/splunk/etc/system/local/user-seed.conf, mode: '0644' }

- name: Adding Apps
  get_url:
    url: https://s3-eu-west-1.amazonaws.com/cloudformation-eu-west-1-791682668801/{{item}}
    dest: /opt/splunk/etc/apps/
  with_items:
    - ta-nmon-technical-addon-for-nmon-performance-monitor_1333.tgz
    - nmon-performance-monitor-for-unix-and-linux-systems_1916.tgz

- name: Configuring splunk
  shell: '/opt/splunk/bin/splunk enable boot-start --accept-license -user splunk'
  
- name: Starting Splunk
  shell: '/opt/splunk/bin/splunk start'