---
- name: Removing NTP packages...
  yum:
    name: "{{ packages_to_remove }}"
    state: absent

- name: Installing default packages {{ packages }}
  yum:
    name: "{{ packages_to_install }}"

- name: Creating template /etc/awslogs/awscli.conf
  template:
    src: /etc/awslogs/awscli.conf
    dest: /etc/awslogs/awscli.conf
    owner: root
    group: root
    mode: 0644

- name: Creating template /etc/awslogs/awslogs.conf
  template:
    src: /etc/awslogs/awslogs.conf
    dest: /etc/awslogs/awslogs.conf
    owner: root
    group: root
    mode: 0644    

- name: Creating template /etc/cfn/cfn-hup.conf
  template:
    src: /etc/cfn/cfn-hup.conf
    dest: /etc/cfn/cfn-hup.conf
    owner: root
    group: root
    mode: 0644    

- name: Creating template /etc/cfn/hooks.d/cfn-auto-reloader.conf
  template:
    src: /etc/cfn/hooks.d/cfn-auto-reloader.conf
    dest: /etc/cfn/hooks.d/cfn-auto-reloader.conf
    owner: root
    group: root
    mode: 0644    

- name: Creating template .bashrc 
  template:
    src: /home/ec2-user/.bashrc
    dest: /home/ec2-user/.bashrc
    owner: root
    group: root
    mode: 0644    

- name: Tagging root volume
  template:
    src: /root/tag_root_volume.sh
    dest: /root/tag_root_volume.sh
    owner: root
    group: root
    mode: 0600    

- name: Installing AWS Inspector Agent
  command: wget -q -O - https://d1wk0tztpsntt1.cloudfront.net/linux/latest/install | sudo bash -s

- name: Configuring yum-cron-hourly
  command: sudo sed -ibckp -E 's/^update_cmd.*/update_cmd = security/;s/^(update_messages|download_updates|apply_updates).*/\\1 = yes/' /etc/yum/yum-cron-hourly.conf

- name: Configuring yum-cron
  command: sudo sed -ibckp -E 's/^(update_messages|download_updates|apply_updates).*/\\1 = yes/' /etc/yum/yum-cron.conf

- name: Tagging root volume
  command: sudo /root/tag_root_volume.sh {{ Region }} {{ StackName }}

- name: Enabling awslogs service
  service:
    name: awslogs
    enabled: yes

- name: Enabling cfn-hup service
  service:
    name: awslogs
    enabled: yes

- name: Enabling yum-cron service
  service:
    name: awslogs
    enabled: yes

- name: Enabling chronyd service
  service:
    name: awslogs
    enabled: yes
