---
#
# FILE: main.yaml
#
# DESCRIPTION: This file contains the base configuration for all host in the 
#   stack. It mainly configure the 
#
#
- name: Removing obsolete packages
  yum:
    name: "{{ default_packages_to_remove }}"
    state: absent

- name: Installing default packages
  yum:
    name: "{{ default_packages_to_install }}"

- name: Creating directory /etc/cfn/hooks.d
  file:
    path: /etc/cfn/hooks.d
    state: directory
    mode: 0755

- name: Creating templates
  template:
    src: 'templates{{item}}'
    dest: '{{item}}'
    owner: root
    group: root
    mode: 0644
  with_items:
    - /etc/awslogs/awscli.conf
    - /etc/awslogs/awslogs.conf
    - /etc/cfn/cfn-hup.conf
    - /etc/cfn/hooks.d/cfn-auto-reloader.conf

- name: Creating template .bashrc 
  template:
    src: templates/home/ec2-user/.bashrc
    dest: /home/ec2-user/.bashrc
    owner: root
    group: root
    mode: 0644    

- name: Copying /root/tag_root_volume.sh
  file:
    src: files/root/tag_root_volume.sh
    dest: /root/tag_root_volume.sh
    owner: root
    group: root
    mode: 0700

- name: Check if AWS Inspector Agent is installed
  yum:
    list=AwsAgent
  register: is_installed

- name: Downloading AWS Inspector Agent
  get_url:
    url: https://d1wk0tztpsntt1.cloudfront.net/linux/latest/install
    dest: /root/AWSInspectorAgent
    mode: 0700
  when: (is_installed.results|length == 1) or (is_installed.results[1].yumstate != 'installed') 

- name: Installing AWS Inspector Agent
  shell: /root/AWSInspectorAgent
  when: (is_installed.results|length == 1) or (is_installed.results[1].yumstate != 'installed') 

- name: Configuring yum-cron-hourly (update_cmd = security)
  lineinfile:
    path: /etc/yum/yum-cron-hourly.conf
    regexp: '^update_cmd.*'
    line: 'update_cmd = security'

- name: Configuring yum-cron-hourly (update_messages|download_updates|apply_updates = yes)
  replace:
    path: /etc/yum/yum-cron-hourly.conf
    regexp: '^(update_messages|download_updates|apply_updates).*'
    replace: '\1 = yes'
    
- name: Configuring yum-cron (update_messages|download_updates|apply_updates = yes)
  replace:
    path: /etc/yum/yum-cron.conf
    regexp: '^(update_messages|download_updates|apply_updates).*'
    replace: '\1 = yes'

- name: Tagging root volume
  script: /root/tag_root_volume.sh {{Region}} {{StackName}}

- name: Enabling services
  service:
    name: '{{item}}'
    state: started
    enabled: yes
  with_items:
    - awslogs
    - cfn-hup
    - yum-cron
    - chronyd
