#
# FILE: efs.yaml
#
# DESCRIPTION: This nested stack creates an EFS FileSystem
#
---
AWSTemplateFormatVersion: "2010-09-09"
Description: 'This nested-stack sets up an EFS FileSystem'
Parameters: 
  ParentVpcStack: 
    Description: 'Enter the name of the VPC Stack where the AutoScalingGroup will reside'
    Type: String
    MinLength: 1
    ConstraintDescription: 'must be the name of the VPC stack'
  ParentStack:
    Description: 'Enter the name of the Stack calling this nested stack'
    Type: String
    MinLength: 1
    ConstraintDescription: 'must be the name of the Parent stack'

Resources: 

  #----------------------------------------------------------------------------
  #
  # AWS EFS
  #
  # We create the filesystem used by the instance to share valuable data between
  #   scaling events
  #
  FileSystem:
    Type: 'AWS::EFS::FileSystem'
    Properties: 
      Encrypted: true
      FileSystemTags:
        - Key: PLATFORM
          Value: 
            'Fn::ImportValue': !Sub '${ParentVpcStack}-StackName'
        - Key: Name
          Value: !Sub '${ParentStack}-FileSystem'
      PerformanceMode: generalPurpose
  MountTargetA:
    Type: 'AWS::EFS::MountTarget'
    Properties:
      FileSystemId: !Ref FileSystem
      SecurityGroups:
        - 'Fn::ImportValue': !Sub '${ParentVpcStack}-SecurityGroupEFS'
      SubnetId: 
        'Fn::ImportValue': !Sub '${ParentVpcStack}-SubnetPrivateAZA'
  MountTargetB:
    Type: 'AWS::EFS::MountTarget'
    Properties:
      FileSystemId: !Ref FileSystem
      SecurityGroups:
        - 'Fn::ImportValue': !Sub '${ParentVpcStack}-SecurityGroupEFS'
      SubnetId: 
        'Fn::ImportValue': !Sub '${ParentVpcStack}-SubnetPrivateAZB'

Outputs: 
  FileSystem: 
    Description: 'The FileSystem'
    Value: !Ref FileSystem
  MountTargetA: 
    Description: 'The MountTargetA'
    Value: !Ref MountTargetA
  MountTargetB: 
    Description: 'The MountTargetB'
    Value: !Ref MountTargetB
