#
# FILE: elb-app.yaml
#
# DESCRIPTION: This stack an Application Load Balancer and the corresponding
#   alarms.
#
---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'This netsted stack create an ElasticLoadBalancer'
Parameters: 
  ParentVpcStack: 
    Description: 'Enter the name of the VPC Stack where the LoadBalancer will reside'
    Type: String
    MinLength: 1
  HealthCheckPath:
    Description: 'The path to check'
    Type: String
    MinLength: 1
  HealthCheckPort:
    Description: 'The port to check'
    Type: Number
  ListenerPort:
    Description: 'The port to listen to'
    Type: Number
  Scheme:
    Description: 'Whether the load balancer is internet-facing or internal'
    Type: String
    AllowedValues:
      - internal
      - internet-facing
    Default: internet-facing
  SubDomainName:
    Description: 'The subdomain of the Internal DNS resolution'
    Type: String
Conditions:
  IsPublic: !Equals [!Ref Scheme, 'internet-facing']
  HasSubDomainName: !Not [!Equals [!Ref SubDomainName, '']]
Resources: 

  #----------------------------------------------------------------------------
  #
  # AWS Application LoadBalancer
  #
  # We create a set of alarms for this specific load balancer, in order to alert
  #   us if something start to go astray...
  #
  LoadBalancer:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Scheme: !Ref Scheme
      SecurityGroups: !If
        - IsPublic
        - - 'Fn::ImportValue': !Sub '${ParentVpcStack}-SecurityGroupPublic'
        - - 'Fn::ImportValue': !Sub '${ParentVpcStack}-SecurityGroupPrivate'
      Subnets: !If
        - IsPublic
        - - 'Fn::ImportValue': !Sub '${ParentVpcStack}-SubnetPublicAZA'
          - 'Fn::ImportValue': !Sub '${ParentVpcStack}-SubnetPublicAZB'
        - - 'Fn::ImportValue': !Sub '${ParentVpcStack}-SubnetPrivateAZA'
          - 'Fn::ImportValue': !Sub '${ParentVpcStack}-SubnetPrivateAZB'
      Tags: 
        - Key: PLATFORM
          Value: 
            'Fn::ImportValue': !Sub '${ParentVpcStack}-StackName'
        - Key: Name
          Value: !Sub '${AWS::StackName}-LoadBalancer'
  TargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: !Ref HealthCheckPath
      HealthCheckTimeoutSeconds: 2
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: '200-299'
      Port: !Ref HealthCheckPort
      Protocol: HTTP
      Tags:
        - Key: PLATFORM
          Value: 
            'Fn::ImportValue': !Sub '${ParentVpcStack}-StackName'
        - Key: Name
          Value: !Sub '${AWS::StackName}-TargetGroup'
      VpcId:
        'Fn::ImportValue': !Sub '${ParentVpcStack}-Vpc'
      TargetGroupAttributes:
        - Key: 'deregistration_delay.timeout_seconds'
          Value: 30
  Listener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      DefaultActions:
      - TargetGroupArn: !Ref TargetGroup
        Type: forward
      LoadBalancerArn: !Ref LoadBalancer
      Port: !Ref ListenerPort
      Protocol: HTTP

  #----------------------------------------------------------------------------
  #
  # AWS Route53
  #
  # We create the internal DNS RecordSet
  #
  RecordSet:
    Condition: HasSubDomainName
    Type: 'AWS::Route53::RecordSet'
    Properties:
      AliasTarget:
        HostedZoneId: !GetAtt LoadBalancer.CanonicalHostedZoneID
        DNSName: !GetAtt LoadBalancer.DNSName
      HostedZoneId:
        'Fn::ImportValue': !Sub '${ParentVpcStack}-HostedZone'
      Name: !Sub
      - '${SubDomainName}.${HostedZoneName}'
      - SubDomainName: !Ref SubDomainName
        HostedZoneName: 
          'Fn::ImportValue': !Sub '${ParentVpcStack}-HostedZoneName'
      Type: A

  #----------------------------------------------------------------------------
  #
  # AWS CloudWatch Alarms
  #
  # We create a set of alarms for this specific load balancer, in order to alert
  #   us if something start to go astray...
  #
  HTTPCodeELB5XXCountTooHighAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'Application load balancer returns 5XX HTTP status codes'
      Namespace: 'AWS/ApplicationELB'
      MetricName: HTTPCode_ELB_5XX_Count
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      ComparisonOperator: GreaterThanThreshold
      Threshold: 0
      AlarmActions:
        - 'Fn::ImportValue': !Sub '${ParentVpcStack}-TopicHealth'
      Dimensions:
        - Name: LoadBalancer
          Value: !GetAtt LoadBalancer.LoadBalancerFullName
  HTTPCodeTarget5XXCountTooHighAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'Application load balancer receives 5XX HTTP status codes from targets'
      Namespace: 'AWS/ApplicationELB'
      MetricName: HTTPCode_Target_5XX_Count
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      ComparisonOperator: GreaterThanThreshold
      Threshold: 0
      AlarmActions:
        - 'Fn::ImportValue': !Sub '${ParentVpcStack}-TopicHealth'
      Dimensions:
        - Name: LoadBalancer
          Value: !GetAtt LoadBalancer.LoadBalancerFullName
  RejectedConnectionCountTooHighAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'Application load balancer rejected connections because the load balancer had reached its maximum number of connections'
      Namespace: 'AWS/ApplicationELB'
      MetricName: RejectedConnectionCount
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      ComparisonOperator: GreaterThanThreshold
      Threshold: 0
      AlarmActions:
        - 'Fn::ImportValue': !Sub '${ParentVpcStack}-TopicHealth'
      Dimensions:
        - Name: LoadBalancer
          Value: !GetAtt LoadBalancer.LoadBalancerFullName
  TargetConnectionErrorCountTooHighAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'Application load balancer could not connect to targets'
      Namespace: 'AWS/ApplicationELB'
      MetricName: TargetConnectionErrorCount
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      ComparisonOperator: GreaterThanThreshold
      Threshold: 0
      AlarmActions:
        - 'Fn::ImportValue': !Sub '${ParentVpcStack}-TopicHealth'
      Dimensions:
        - Name: LoadBalancer
          Value: !GetAtt LoadBalancer.LoadBalancerFullName

Outputs: 
  LoadBalancer: 
    Description: 'The LoadBalancer ARN'
    Value: !Ref LoadBalancer
  DNSName: 
    Description: 'The LoadBalancer DNSName'
    Value: !GetAtt LoadBalancer.DNSName
  CanonicalHostedZoneID:
    Description: 'The LoadBalancer ARN'
    Value: !GetAtt LoadBalancer.CanonicalHostedZoneID
  TargetGroup: 
    Description: 'The TargetGroup ARN'
    Value: !Ref TargetGroup
  HTTPCodeELB5XXCountTooHighAlarm:
    Description: 'The Alarm ARN'
    Value: !GetAtt HTTPCodeELB5XXCountTooHighAlarm.Arn
  HTTPCodeTarget5XXCountTooHighAlarm:
    Description: 'The Alarm ARN'
    Value: !GetAtt HTTPCodeTarget5XXCountTooHighAlarm.Arn
  RejectedConnectionCountTooHighAlarm:
    Description: 'The Alarm ARN'
    Value: !GetAtt RejectedConnectionCountTooHighAlarm.Arn
  TargetConnectionErrorCountTooHighAlarm:
    Description: 'The Alarm ARN'
    Value: !GetAtt TargetConnectionErrorCountTooHighAlarm.Arn
