#
# FILE: elb-app.yaml
#
# DESCRIPTION: This stack is a nested stack that can be used by application
#   require a Load Balancer in conjonction with an AutoScalingGroup
#
---
AWSTemplateFormatVersion: '2010-09-09'

Description: 'This netsted stack create an ElasticLoadBalancer'

Metadata: 
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'Parent Stack'
      Parameters:
      - ParentVpcStack
    - Label: 
        default: 'Load Balancer Parameter'
      Parameters:
      - HealthCheckPath
      - HealthCheckPort
      - ListenerPort
      - TopicArn
      
Parameters: 
  ParentVpcStack: 
    Description: 'Enter the name of the VPC Stack where the LoadBalancer will reside'
    Type: String
    MinLength: 1
    
  HealthCheckPath:
    Description: 'The path to check'
    Type: String
    MinLength: 1

  HealthCheckPort:
    Description: 'The port to check'
    Type: Number

  ListenerPort:
    Description: 'The port to listen to'
    Type: Number

Resources: 

  #----------------------------------------------------------------------------
  #
  # AWS Application LoadBalancer
  #
  # We create a set of alarms for this specific load balancer, in order to alert
  #   us if something start to go astray...
  #
  LoadBalancer:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Scheme: internet-facing
      SecurityGroups:
      - 'Fn::ImportValue': !Sub '${ParentVpcStack}-SecurityGroupPublic'
      Subnets: 
        - 'Fn::ImportValue': !Sub '${ParentVpcStack}-SubnetPublicAZA'
        - 'Fn::ImportValue': !Sub '${ParentVpcStack}-SubnetPublicAZB'
      Tags: 
        - Key: PLATFORM
          Value: 
            'Fn::ImportValue': !Sub '${ParentVpcStack}-StackName'
        - Key: Name
          Value: !Sub '${AWS::StackName}-LoadBalancer'
  TargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: !Ref HealthCheckPath
      HealthCheckTimeoutSeconds: 2
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: '200-299'
      Port: !Ref HealthCheckPort
      Protocol: HTTP
      Tags:
        - Key: PLATFORM
          Value: 
            'Fn::ImportValue': !Sub '${ParentVpcStack}-StackName'
        - Key: Name
          Value: !Sub '${AWS::StackName}-TargetGroup'
      VpcId:
        'Fn::ImportValue': !Sub '${ParentVpcStack}-Vpc'
      TargetGroupAttributes:
        - Key: 'deregistration_delay.timeout_seconds'
          Value: 30
  Listener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      DefaultActions:
      - TargetGroupArn: !Ref TargetGroup
        Type: forward
      LoadBalancerArn: !Ref LoadBalancer
      Port: !Ref ListenerPort
      Protocol: HTTP

  #----------------------------------------------------------------------------
  #
  # AWS CloudWatch Alarms
  #
  # We create a set of alarms for this specific load balancer, in order to alert
  #   us if something start to go astray...
  #
  LoadBalancer5XXTooHighAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'Application load balancer returns 5XX HTTP status codes'
      Namespace: 'AWS/ApplicationELB'
      MetricName: HTTPCode_ELB_5XX_Count
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      ComparisonOperator: GreaterThanThreshold
      Threshold: 0
      AlarmActions:
        - 'Fn::ImportValue': !Sub '${ParentVpcStack}-TopicHealth'
      Dimensions:
        - Name: LoadBalancer
          Value: !GetAtt LoadBalancer.LoadBalancerFullName
  TargetGroup5XXTooHighAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'Application load balancer receives 5XX HTTP status codes from targets'
      Namespace: 'AWS/ApplicationELB'
      MetricName: HTTPCode_Target_5XX_Count
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      ComparisonOperator: GreaterThanThreshold
      Threshold: 0
      AlarmActions:
        - 'Fn::ImportValue': !Sub '${ParentVpcStack}-TopicHealth'
      Dimensions:
        - Name: LoadBalancer
          Value: !GetAtt LoadBalancer.LoadBalancerFullName
  LoadBalancerConnectionCountTooHighAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'Application load balancer rejected connections because the load balancer had reached its maximum number of connections'
      Namespace: 'AWS/ApplicationELB'
      MetricName: RejectedConnectionCount
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      ComparisonOperator: GreaterThanThreshold
      Threshold: 0
      AlarmActions:
        - 'Fn::ImportValue': !Sub '${ParentVpcStack}-TopicHealth'
      Dimensions:
        - Name: LoadBalancer
          Value: !GetAtt LoadBalancer.LoadBalancerFullName
  TargetGroupConnectionErrorCountTooHighAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'Application load balancer could not connect to targets'
      Namespace: 'AWS/ApplicationELB'
      MetricName: TargetConnectionErrorCount
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      ComparisonOperator: GreaterThanThreshold
      Threshold: 0
      AlarmActions:
        - 'Fn::ImportValue': !Sub '${ParentVpcStack}-TopicHealth'
      Dimensions:
        - Name: LoadBalancer
          Value: !GetAtt LoadBalancer.LoadBalancerFullName

Outputs: 
  DNSName: 
    Description: 'The LoadBalancer DNSName'
    Value: !Sub '${LoadBalancer.DNSName}'
  LoadBalancer: 
    Description: 'The LoadBalancer ARN'
    Value: !Sub '${LoadBalancer}'
  TargetGroup: 
    Description: 'The TargetGroup ARN'
    Value: !Sub '${TargetGroup}'
