---
#
# FILE: main.yaml
#
# DESCRIPTION: Install and configure the OpenLDAP
#
#
- name: Creating cleanup playbook
  include_role: name=common tasks_from=cleanup 
  with_items:
    - files/root/playbooks/cleanup.yaml
  loop_control:
    loop_var: cleanup_playbook

- name: Installing OpenLDAP packages
  yum:
    name: '{{item}}'
  with_items:
    - openldap
    - openldap-clients
    - openldap-servers
    - python-devel
    - openldap-devel
    - gcc

- name: Installing Pip modules
  pip:
    name: python-ldap

- name: Copying DB_CONFIG
  copy:
    src: /usr/share/openldap-servers/DB_CONFIG.example
    dest: /var/lib/ldap/DB_CONFIG

- name: Starting slapd
  service:
    name: 'slapd'
    state: started

- name: Creating directory /root/openldap
  file:
    path: /root/openldap
    state: directory
    mode: 0700

- name: Creating templates
  template:
    src: 'templates{{item}}'
    dest: '{{item}}'
    owner: root
    group: root
    mode: 0700
  with_items:
    - /root/openldap/update_users.sh

- name: Scheduling cron for /root/openldap/update_users.sh
  cron:
    name: 'update_users'
    minute: "*/10"
    job: /root/openldap/update_users.sh
    user: root
    cron_file: update_users

- name: Bootstrapping directory
  ldap_attr:
    dn: olcDatabase={2}bdb,cn=config
    name: "{{ item.key }}"
    values: "{{ item.value }}"
    state: exact
  with_dict:
    olcSuffix: '{{RootDC}}'
    olcRootDN: 'cn=Manager,{{RootDC}}'
    olcRootPW: '{{ManagerPassword}}'

- name: Enabling services
  service:
    name: '{{item}}'
    state: restarted
    enabled: yes
  with_items:
    - slapd
