#
# FILE: 02-inspector.yaml
#
# DESCRIPTION: This Stack create the AWS Inspector element to be able to assess the different stack security 
#
# TODO: 
# - Should update list of packages rules with:
# ?> aws inspector list-rules-packages
# - Let the creator of the User of the stack choose the rules package to use.
---
AWSTemplateFormatVersion: "2010-09-09"
Description: "This stack creates the AWS Inspector elements"
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'Parent VPC Stack'
      Parameters:
      - ParentVpcStack
Parameters: 
  ParentVpcStack: 
    Description: 'Enter the name of the VPC stack containing all the instance you want to scan for vulnerability' 
    Type: String
    MinLength: 1
    ConstraintDescription: 'must be the name of the parent VPC stack'
Resources:
  ResourceGroup: 
    Type: 'AWS::Inspector::ResourceGroup'
    Properties:
      ResourceGroupTags: 
        - Key: PLATFORM
          Value: 
            'Fn::ImportValue': !Sub '${ParentVpcStack}-StackName'
  AssessmentTarget: 
    Type: 'AWS::Inspector::AssessmentTarget'
    Properties:
      AssessmentTargetName: !Sub 'Assessment Target for the ${ParentVpcStack} Stack'
      ResourceGroupArn: !GetAtt ResourceGroup.Arn
  AssessmentTemplate:
    Type: 'AWS::Inspector::AssessmentTemplate'
    Properties:
      AssessmentTargetArn: !GetAtt AssessmentTarget.Arn
      DurationInSeconds: 3600
      AssessmentTemplateName: !Sub 'Assessment Template for the ${ParentVpcStack} Stack'
      RulesPackageArns: 
        - 'arn:aws:inspector:us-west-2:758058086616:rulespackage/0-11B9DBXp'
      UserAttributesForFindings: 
        - Resource Tag
Outputs: 
  