#
# FILE: 03-splunk.yaml
#
# DESCRIPTION: This Stack create a Splunk Host as well as an Internet facing LoadBalancer.
#
# BEWARE: that it uses a publicly accessible S3 bucket to retrieve it instalation RPMs/sources.
#   splunk-7.1.1-8f0ead9ec3db-linux-2.6-x86_64.rpm: https://download.splunk.com/products/splunk/releases/7.1.1/linux/splunk-7.1.1-8f0ead9ec3db-linux-2.6-x86_64.rpm
#   nmon-performance-monitor-for-unix-and-linux-systems_1916.tgz: https://splunkbase.splunk.com/app/1753/
#   ta-nmon-technical-addon-for-nmon-performance-monitor_1333.tgz: https://splunkbase.splunk.com/app/3248/
#
# NOTE: in order to create the AMI mapping you can run the following command. (needs a bit of massaging: 
#   should extract the ami and the region name, and output everything in the YAML compatible format)
# 
# for region in $(aws ec2 describe-regions --query 'Regions[*].{Name:RegionName}' --output text); do
#   aws --region $region ec2 describe-images --owners amazon --filters "Name=name,Values=amzn-ami-hvm-$(date +%Y)*-gp2" "Name=architecture,Values=x86_64" "Name=root-device-type,Values=ebs" --query 'Images[*].{ID:ImageId}'
# done
#
# TODO: 
# - Should use https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html#aws-specific-parameter-types
# - Provide LDAP authentication http://docs.splunk.com/Documentation/Splunk/7.1.1/Security/SetupuserauthenticationwithLDAP
# - Should provide alert when the platform is unhealthy
#
---
AWSTemplateFormatVersion: "2010-09-09"
Description: "This stack create a Splunk host and install the NMON application"
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'Parent Stack'
      Parameters:
      - ParentVpcStack
    - Label:
        default: 'EC2 Parameters'
      Parameters:
      - KeyName
      - SplunkInstanceType
    - Label:
        default: 'Splunk Parameters'
      Parameters:
      - SplunkAdminPassword
Parameters: 
  ParentVpcStack: 
    Description: "Enter the name of the VPC Stack where Splunk will reside"
    Type: String
    Default: ''
  KeyName: 
    Description: "Optional Key Pair to connect through SSH"
    Type: "AWS::EC2::KeyPair::KeyName"
  SplunkInstanceType:
    Description: 'The instance type of the Jenkins master.'
    Type: String
    Default: 'c4.large'    
  SplunkAdminPassword: 
    Description: "Enter the default Admin password for Splunk"
    Type: String
    Default: ''
    NoEcho: true
Mappings:
  RegionMap:
    'ap-south-1':
      AMI: 'ami-76d6f519'
    'eu-west-3':
      AMI: 'ami-969c2deb'
    'eu-west-2':
      AMI: 'ami-a36f8dc4'
    'eu-west-1':
      AMI: 'ami-ca0135b3'
    'ap-northeast-2':
      AMI: 'ami-c10fa6af'
    'ap-northeast-1':
      AMI: 'ami-92df37ed'
    'sa-east-1':
      AMI: 'ami-3885d854'
    'ca-central-1':
      AMI: 'ami-338a0a57'
    'ap-southeast-1':
      AMI: 'ami-de90a5a2'
    'ap-southeast-2':
      AMI: 'ami-423bec20'
    'eu-central-1':
      AMI: 'ami-9a91b371'
    'us-east-1':
      AMI: 'ami-14c5486b'
    'us-east-2':
      AMI: 'ami-922914f7'
    'us-west-1':
      AMI: 'ami-25110f45'
    'us-west-2':
      AMI: 'ami-e251209a'    
Conditions:
  HasKeyName: !Not [!Equals [!Ref KeyName, '']]
Resources: 
  #
  # Let's create the SecurityGroup for the ELB LoadBalancer. Basically it should only allow traffic on the HTTP/S port
  #   from the Internet. If you want to restrict the IP from which to accept traffic, do it here. you can have a look 
  #   at the 01-vpc.yaml, and more specifically the SecurityGroupDMZ for an example.
  #
  SecurityGroupELB:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Security Group to access Splunk ELB'
      VpcId:
        'Fn::ImportValue': !Sub '${ParentVpcStack}-Vpc'
      SecurityGroupIngress:
      - CidrIp : "0.0.0.0/0"
        FromPort: 443
        ToPort: 443
        IpProtocol: tcp
      - CidrIp : "0.0.0.0/0"
        FromPort: 80
        ToPort: 80
        IpProtocol: tcp
      Tags: 
        - Key: PLATFORM
          Value: 
            'Fn::ImportValue': !Sub '${ParentVpcStack}-StackName'
        - Key: Name
          Value: !Sub '${AWS::StackName}-SecurityGroupELB'
  LoadBalancerSplunk:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Scheme: 'internet-facing'
      SecurityGroups:
      - !Ref SecurityGroupELB
      Subnets: 
        - 'Fn::ImportValue': !Sub '${ParentVpcStack}-SubnetPublicAZA'
        - 'Fn::ImportValue': !Sub '${ParentVpcStack}-SubnetPublicAZB'
      Tags: 
        - Key: PLATFORM
          Value: 
            'Fn::ImportValue': !Sub '${ParentVpcStack}-StackName'
        - Key: Name
          Value: !Sub '${AWS::StackName}-LoadBalancerSplunk'
  TargetGroupSplunk:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: '/en-GB/account/login'
      HealthCheckTimeoutSeconds: 2
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: '200-299'
      Port: 8000
      Protocol: HTTP
      Tags:
        - Key: PLATFORM
          Value: 
            'Fn::ImportValue': !Sub '${ParentVpcStack}-StackName'
        - Key: Name
          Value: !Sub '${AWS::StackName}-TargetGroupSplunk'
      VpcId:
        'Fn::ImportValue': !Sub '${ParentVpcStack}-Vpc'
      TargetGroupAttributes:
        - Key: 'deregistration_delay.timeout_seconds'
          Value: 30
      Targets:
        - Id: !Ref SplunkHost
    DependsOn: SplunkHost
  ListenerSplunk:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      DefaultActions:
      - TargetGroupArn: !Ref TargetGroupSplunk
        Type: forward
      LoadBalancerArn: !Ref LoadBalancerSplunk
      Port: 80
      Protocol: HTTP
  #
  # Let's create the Splunk instance.
  # 
  # TODO: Should have a specific SecurityGroup for the instance in order to only allow traffic on port 8000 (default
  #   Splunk port). Further more I should enable SSL traffic, but beware that the load balancer might not allow 
  #   communications with a host presenting a self-signed certificate.
  #
  SecurityGroupSplunk:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Security Group to access the Splunk instance'
      VpcId:
        'Fn::ImportValue': !Sub '${ParentVpcStack}-Vpc'
      SecurityGroupIngress:
      - SourceSecurityGroupId: 
          !Ref 'SecurityGroupELB'
        FromPort: 8000
        ToPort: 8000
        IpProtocol: tcp
      Tags: 
        - Key: PLATFORM
          Value: 
            'Fn::ImportValue': !Sub '${ParentVpcStack}-StackName'
        - Key: Name
          Value: !Sub '${AWS::StackName}-SecurityGroupSplunk'
  SplunkHost: 
    Type: 'AWS::EC2::Instance'
    Metadata:
      AWS::CloudFormation::Init:
        #
        # The logs for the cfn-init command are available in the instance in /var/log/cfn-init-cmd.log 
        #
        configSets: 
          default: [ Bootstrap, InstallSplunk, InstallSplunkApps, StartSplunk ]
        Bootstrap:
          packages:
            yum:
              htop: []
              awslogs: []
              yum-cron: []
          files: 
            '/home/ec2-user/.bashrc':
              content: !Sub |
                [ -f /etc/bashrc ] && . /etc/bashrc
                alias c=clear
                alias l='ls -l'
                alias vi=vim
              mode: '000600'
              owner: 'ec2-user'
              group: 'ec2-user'
            '/root/tag_root_volume.sh':
              content: !Sub |
                #!/bin/bash
                STACK_NAME=${AWS::StackName}
                REGION=${AWS::Region}
                echo "Tagging Root volume..."
                INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
                VOLUME_ID=$(aws --region $REGION ec2 describe-volumes --filters "Name=attachment.instance-id,Values=$INSTANCE_ID" "Name=attachment.device,Values=/dev/xvda" --query "Volumes[0].VolumeId" --output text)
                PLATFORM=$(aws --region $REGION ec2 describe-instances --instance-ids $INSTANCE_ID --query "Reservations[0].Instances[0].Tags" --output table | grep PLATFORM | cut -d '|' -f 3 | sed -e 's/ //g')
                aws --region $REGION ec2 create-tags --resources $VOLUME_ID --tag "Key=Name,Value=$STACK_NAME-VolumeRoot"
                aws --region $REGION ec2 create-tags --resources $VOLUME_ID --tag "Key=PLATFORM,Value=$PLATFORM"
              mode: '000744'
              owner: 'root'
              group: 'root'
          commands:
            '01_install_aws_inspector': 
              command: 'wget -q -O - https://d1wk0tztpsntt1.cloudfront.net/linux/latest/install | sudo bash -s'
            '02_yum_cron_hourly.conf':
              command: "sudo sed -ibckp -E 's/^update_cmd.*/update_cmd = security/;s/^(update_messages|download_updates|apply_updates).*/\\1 = yes/' /etc/yum/yum-cron-hourly.conf"
            '03_yum_cron.conf':
              command: "sudo sed -ibckp -E 's/^(update_messages|download_updates|apply_updates).*/\\1 = yes/' /etc/yum/yum-cron.conf"
            '04_tag_root_volume':
              command: "sudo /root/tag_root_volume.sh"
            '05_mkfs': 
              command: 'sudo mkfs -t ext4 /dev/xvdb'
            '06_mount': 
              command: 'sudo mkdir -p /opt/splunk && sudo mount /dev/xvdb /opt/splunk'
            '07_fix_fstab': 
              command: 'echo "/dev/xvdb /opt/splunk ext4 rw,relatime,data=ordered 0 2" >> /etc/fstab'
          services:
            sysvinit:
              yum-cron: 
                enabled: true
                ensureRunning: true
        InstallSplunk: 
          packages: 
            rpm: 
              splunk: 'https://s3-eu-west-1.amazonaws.com/cloudformation-eu-west-1-791682668801/splunk-7.1.1-8f0ead9ec3db-linux-2.6-x86_64.rpm'
          files:
            '/opt/splunk/etc/system/local/user-seed.conf':
              content: !Sub |
                [user_info]
                USERNAME = admin
                PASSWORD = ${SplunkAdminPassword}
              mode: "000644"
              owner: "root"
              group: "root"
          commands:
            '01_splunk_enable':
              command: 'sudo /opt/splunk/bin/splunk enable boot-start --accept-license -user splunk'
              cwd: '~'
        InstallSplunkApps: 
          files:
            '/opt/splunk/etc/apps/':
              source: 'https://s3-eu-west-1.amazonaws.com/cloudformation-eu-west-1-791682668801/nmon-performance-monitor-for-unix-and-linux-systems_1916.tgz'
#            '/opt/splunk/etc/apps/':
#              source: 'https://s3-eu-west-1.amazonaws.com/cloudformation-eu-west-1-791682668801/ta-nmon-technical-addon-for-nmon-performance-monitor_1333.tgz'
        StartSplunk:              
          commands:
            "01_splunk_start":
              command: 'sudo /opt/splunk/bin/splunk start'
    Properties: 
      DisableApiTermination: false
      InstanceInitiatedShutdownBehavior: stop
      IamInstanceProfile: 
        'Fn::ImportValue': !Sub '${ParentVpcStack}-InstanceProfileTagEC2Instance'      
      ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region', AMI]
      InstanceType: !Ref SplunkInstanceType
      KeyName: !If [HasKeyName, !Ref KeyName, !Ref 'AWS::NoValue']
      SecurityGroupIds: 
        - 'Fn::ImportValue': !Sub '${ParentVpcStack}-SecurityGroupPrivate'
        - !Ref SecurityGroupSplunk
      SubnetId: 
        'Fn::ImportValue': !Sub '${ParentVpcStack}-SubnetPrivateAZA'
      Volumes : 
        - VolumeId: !Ref VolumeData
          Device: '/dev/xvdb'
      Monitoring: false
      UserData:
        'Fn::Base64': !Sub |
          #!/bin/bash
          yum-config-manager --enable epel
          yum update -y
          yum install -y aws-cfn-bootstrap
          /opt/aws/bin/cfn-init --verbose --stack ${AWS::StackName} --resource BastionHost --region ${AWS::Region}
      Tags: 
        - Key: PLATFORM
          Value: 
            'Fn::ImportValue': !Sub '${ParentVpcStack}-StackName'
        - Key: Name
          Value: !Sub '${AWS::StackName}-SplunkHost'
    DependsOn: VolumeData
  VolumeData:
    Type: 'AWS::EC2::Volume'
    Properties:
      Size: 500
      Encrypted: true
      VolumeType: gp2
      AvailabilityZone: 
        'Fn::ImportValue': !Sub '${ParentVpcStack}-AvailabilityZoneSubnetPublicAZA'
      Tags: 
        - Key: PLATFORM
          Value: 
            'Fn::ImportValue': !Sub '${ParentVpcStack}-StackName'
        - Key: Name
          Value: !Sub '${AWS::StackName}-VolumeData'
Outputs: 
  InstanceId: 
    Description: "InstanceId of the newly created Splunk instance"
    Value: !Ref SplunkHost
    Export:
      Name: !Sub '${AWS::StackName}-InstanceId'
  DNSName: 
    Description: "Public DNS address of the internet facing ELB"
    Value: !GetAtt LoadBalancerSplunk.DNSName
    Export:
      Name: !Sub '${AWS::StackName}-DNSName'
      