---
- name: Configuring SSH for IAM User Access
  include_role: name=common tasks_from=configure_asg

- name: Removing obsolete packages
  yum:
    name: 'ntp*'
    state: absent

- name: Installing default packages
  yum:
    name: '{{item}}'
  with_items:
    - awslogs
    - wget
    - htop
    - chrony

- name: Installing ASG signalling
  include_role: name=common tasks_from=configure_bashrc

- name: Configuring SSH for IAM User Access
  include_role: name=common tasks_from=configure_sshd
  when: 
    - HasIAMUserSSHAccess is defined
    - HasIAMUserSSHAccess == true 

- name: Enabling services
  service:
    name: '{{item}}'
    state: started
    enabled: yes
  with_items:
    - chronyd

- name: Removing obsolete packages
  yum: name='{{item}}' state=absent
  with_items:
    - java-1.7.0-openjdk

- name: Adding Maven repository
  get_url: url=https://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo dest=/etc/yum.repos.d/epel-apache-maven.repo mode=644

- name: Fixing maven repository definition
  replace:
    path: /etc/yum.repos.d/epel-apache-maven.repo
    regexp: '\$releasever'
    replace: '7'

- name: Installing default packages
  yum: name='{{item}}'
  with_items:
    - jq
    - git
    - patch
    - docker
    - apache-maven
    - java-1.8.0-openjdk
    - java-1.8.0-openjdk-devel

- name: Creating builder user
  user:
    name: builder
    shell: /bin/bash

- name: Downloading swarm client
  get_url: url=https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/swarm-client/3.14/swarm-client-3.14.jar dest=/home/builder/swarm-client.jar mode=644
  
- name: Creating Directories
  file: path='{{item.path}}' state=directory owner='{{item.owner}}' group='{{item.owner}}' mode=0755
  with_items:
    - { path: /home/builder/.m2/, owner: builder }
  
- name: Templating configuration files
  template: src='templates{{item.src}}' dest='{{item.src}}' owner='{{item.user}}' group='{{item.user}}' mode='{{item.mode}}'
  with_items:
    - { src: /home/builder/.m2/settings.xml, mode: '0600', user: builder }
    - { src: /etc/init.d/jenkins-swarm-client, mode: '0700', user: root }

- name: Creating templates
  template:
    src: 'templates{{item}}'
    dest: '{{item}}'
    owner: root
    group: root
    mode: 0644
  with_items:
    - /etc/awslogs/awscli.conf
    - /etc/awslogs/awslogs.conf

- name: Enabling services
  service: name='{{item}}' state=started enabled=yes
  with_items:
    - awslogs
  notify: restart awslogs

- name: Enabling services
  service: name='{{item}}' state=started enabled=yes
  with_items:
    - jenkins-swarm-client
