---
- name: Removing obsolete packages
  yum: name='{{item}}' state=absent
  with_items:
    - java-1.7.0-openjdk

- name: Adding Maven repository
  get_url: url=http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo dest=/etc/yum.repos.d/epel-apache-maven.repo mode=644

- name: Fixing maven repository definition
  replace:
    path: /etc/yum.repos.d/epel-apache-maven.repo
    regexp: '\$releasever'
    replace: '7'

- name: Installing default packages
  yum: name='{{item}}'
  with_items:
    - jq
    - git
    - patch
    - docker
    - apache-maven
    - java-1.8.0-openjdk
    - java-1.8.0-openjdk-devel

- name: Creating builder user
  user:
    name: builder
    shell: /bin/bash

- name: Downloading swarm client
  get_url: url=https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/swarm-client/3.13/swarm-client-3.13.jar dest=/home/builder/swarm-client.jar mode=644
  
- name: Creating Directories
  file: path='{{item.path}}' state=directory owner='{{item.owner}}' group='{{item.owner}}' mode=0755
  with_items:
    - { path: /home/builder/.m2/, owner: builder }
  
- name: Templating configuration files
  template: src='templates{{item.src}}' dest='{{item.src}}' owner='{{item.user}}' group='{{item.user}}' mode='{{item.mode}}'
  with_items:
    - { src: /home/builder/.m2/settings.xml, mode: '0600', user: builder }
    - { src: /etc/init.d/jenkins-swarm-client, mode: '0700', user: root }

- name: Enabling services
  service: name='{{item}}' state=started enabled=yes
  with_items:
    - jenkins-swarm-client
