---
- name: Creating cleanup playbook
  include_role: name=common tasks_from=cleanup 
  with_items:
    - files/root/playbooks/cleanup.yaml
  loop_control:
    loop_var: cleanup_playbook

- name: Removing obsolete packages
  yum: name='{{item}}' state=absent
  with_items:
    - java-1.7.0-openjdk

- name: Installing default packages
  yum: name='{{item}}'
  with_items:
    - jq
    - patch
    - mysql56
    - py-bcrypt
    - openldap-clients
    - java-1.8.0-openjdk
    - java-1.8.0-openjdk-devel

- name: Instaling required Ruby Gems
  gem: name='{{item}}'
  with_items:
    - aws-sdk
    - daemons
    
- name: Instaling required Pip modules
  pip: name='{{item}}'
  with_items:
    - python-jenkins

- name: Adding Maven repository
  get_url: url=http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo dest=/etc/yum.repos.d/epel-apache-maven.repo mode=644

- name: Adding Jenkins repository
  get_url: url=http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo dest=/etc/yum.repos.d/jenkins.repo mode=644

- name: Import Jenkins Signing Key
  rpm_key: key=https://jenkins-ci.org/redhat/jenkins-ci.org.key state=present

- name: Downloading Groovy
  unarchive:
    src: https://dl.bintray.com/groovy/maven/apache-groovy-binary-2.5.1.zip
    dest: /opt
    remote_src: yes

- name: Installing Groovy
  file: src=/opt/groovy-2.5.1/bin/groovy dest=/usr/bin/groovy state=link  

- name: Fixing maven repository definition
  replace:
    path: /etc/yum.repos.d/epel-apache-maven.repo
    regexp: '\$releasever'
    replace: '7'

- name: Installing Jenkins
  yum: name="{{packages}}"
  vars: 
    packages:
      - jq
      - ant
      - git
      - docker
      - jenkins
      - apache-maven
