---
- name: Install Jenkins plugins
  jenkins_plugin: name='{{item}}' url_username=admin url_password='{{current_password}}'
  with_items:
    - ace-editor
    - ant
    - antisamy-markup-formatter
    - artifactory
    - build-pipeline-plugin
    - build-timeout
    - categorized-view
    - checkstyle
    - cloudbees-folder
    - cobertura
    - compact-columns
    - conditional-buildstep
    - config-file-provider
    - configure-job-column-plugin
    - copyartifact
    - credentials-binding
    - docker-workflow
    - downstream-buildview
    - email-ext
    - emailext-template
    - embeddable-build-status
    - envinject
    - envinject
    - extensible-choice-parameter
    - github-organization-folder
    - git-parameter
    - gitlab-hook
    - gitlab-logo
    - gitlab-merge-request-jenkins
    - gitlab-plugin
    - gradle
    - greenballs
    - groovy
    - groovy-postbuild
    - htmlpublisher
    - http_request
    - javadoc
    - jenkins-multijob-plugin
    - jira
    - job-dsl
    - jqs-monitoring
    - junit
    - ldap
    - mailer
    - matrix-auth
    - parameterized-trigger
    - pipeline-aws
    - pipeline-maven
    - pipeline-stage-view
    - publish-over-ssh
    - rebuild
    - sonar
    - ssh
    - ssh-agent
    - ssh-slaves
    - subversion
    - swarm
    - timestamper
    - token-macro
    - view-job-filters
    - warnings
    - workflow-aggregator
    - ws-cleanup
  register: new_plugin_installed

- include_tasks: restart_and_wait.yaml
  with_items:
    - restarted
  loop_control:
    loop_var: state
  when: new_plugin_installed.changed

  