security:
  anonAccessEnabled: false
  anonAccessToBuildInfosDisabled: true
  ldapSettings:
    OpenLDAP:
      emailAttribute: mail
      ldapPoisoningProtection: true
      ldapUrl: 'ldap://{{LDAPDNSName}}:{{LDAPPort}}'
      search:
        managerDn: '{{LDAPManagerDN}}'
        managerPassword: '{{LDAPManagerPassword}}'
        searchBase: 'ou=People,{{LDAPRootDC}}'
        searchFilter: (uid={0})
        searchSubTree: true
      allowUserToAccessProfile: true
      autoCreateUser: true
      enabled: true
localRepositories: 
  'libs-releases-local': 
    type: maven
    includesPattern: '**/*'
    handleReleases: true
    handleSnapshots: false
  'libs-snapshots-local': 
    type: maven
    includesPattern: '**/*'
    handleReleases: false
    handleSnapshots: true